#!/usr/bin/env python3

import sys
sys.path.insert(0, '.')

from syemte import syemte

track = syemte.Track(bpm=180, sample="thermos")
track.add_silence(48)
for t1 in range(4):
    track.add_notes(6, "a3")
    track.add_notes(6, "a2")
    track.add_notes(6, "g3")
    track.add_notes(6, "g2")
track.add_notes(6, "a3")
track.add_notes(6, "a2")
track.add_notes(6, "g3")
track.add_notes(5, "g2")
track.add_notes(1, "a2")
track.add_notes(5, "gb3")
track.add_notes(1, "gb3")
track.add_notes(6, "gb3")
track.add_notes(5, "f3")
track.add_notes(1, "f3")
track.add_notes(3, "ab3")
track.add_notes(3, "gb3")
track.add_notes(5, "e3")
track.add_notes(1, "e3")
track.add_notes(4, "e3")
track.add_notes(1, "bb2")
track.add_notes(1, "db3")
track.add_notes(5, "gb3")
track.add_notes(1, "gb3")
track.add_notes(6, "gb3")
track.add_notes(5, "b2")
track.add_notes(1, "b2")
track.add_notes(3, "b2")
track.add_notes(3, "gb3")
track.add_notes(5, "e3")
track.add_notes(1, "e3")
track.add_notes(6, "e3")
track.add_notes(5, "ab3")
track.add_notes(1, "a3")
track.add_notes(6, "a3")
track.add_notes(5, "g3")
track.add_notes(1, "g3")
track.add_notes(6, "g3")
for t1 in range(2):
    track.add_notes(6, "a3")
    track.add_notes(6, "a2")
    track.add_notes(6, "g3")
    track.add_notes(6, "g2")

track.export("output/track4.wav")
